version: '3.8'

services:
  db:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=aid
      - MYSQL_USER=youruser
      - MYSQL_PASSWORD=yourpassword
    ports:
      - "3307:3306"

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=3307
      - DB_USER=youruser
      - DB_PASS=yourpassword
      - DB_NAME=aid
    depends_on:
      - db

volumes:
  mysql_data:
